Repository LiskHQ/lisk-core, pull requests merged in 2019-12, with the labels that each got.

#173 Update betanet genesis config - Closes #168
  config/betanet/genesis_block.json
Labels: :white_check_mark: ready

#176 Schema validation error for tx type 7 - Closes #174
  src/transactions/6_in_transfer_transaction.ts
  src/transactions/7_out_transfer_transaction.ts
Labels: :eye: pending review

#178 Update P2P state value from integer to string - Closes #177
  qa/features/peers/list_peers.feature
  qa/support/lisk_util.js
Labels: :eye: pending review

#179 Update peer api schema - Closes #177
  qa/.nvmrc
  qa/api_schema/api_spec.json
  qa/package-lock.json
  qa/package.json
  qa/test/tools/network.js
Labels: status: ready to merge
